/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConexaoBancoDados;
import Controle.Usuario;
import Modelo.ModUsuario;


import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class CadastroUsuario extends javax.swing.JFrame {

  //  ConexaoBancoDados conect = new ConexaoBancoDados();
    ModUsuario modenf = new ModUsuario();
    Usuario control = new Usuario();
    int flag=0;
    
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundCadEmf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeFormEmf = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        CorenFormEmf = new javax.swing.JLabel();
        CagoFormEmf = new javax.swing.JLabel();
        CampoCArgo = new javax.swing.JTextField();
        BtnSalvarCadEmf = new javax.swing.JButton();
        CampoSenha = new javax.swing.JPasswordField();
        BTNpesquisaEnfermeiro = new javax.swing.JButton();
        pesqEnf = new javax.swing.JLabel();
        jTextFieldpesquisa = new javax.swing.JTextField();
        lablCOnfSenha = new javax.swing.JLabel();
        CampoConfSenha = new javax.swing.JPasswordField();
        BTNEcluir = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        CampMatricula = new javax.swing.JTextField();
        LBLCOdigo = new javax.swing.JLabel();
        QuadroLBL = new javax.swing.JLabel();
        BTNnovo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        fundCadEmf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Cadastro de Usuários");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(201, 0, 210, 33);

        NomeFormEmf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        NomeFormEmf.setText("Nome :");
        getContentPane().add(NomeFormEmf);
        NomeFormEmf.setBounds(30, 180, 60, 20);

        campoNome.setEnabled(false);
        getContentPane().add(campoNome);
        campoNome.setBounds(90, 170, 230, 30);

        CorenFormEmf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CorenFormEmf.setText("Senha :");
        getContentPane().add(CorenFormEmf);
        CorenFormEmf.setBounds(30, 230, 70, 30);

        CagoFormEmf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CagoFormEmf.setText("Cargo :");
        getContentPane().add(CagoFormEmf);
        CagoFormEmf.setBounds(340, 170, 60, 30);

        CampoCArgo.setEnabled(false);
        getContentPane().add(CampoCArgo);
        CampoCArgo.setBounds(400, 170, 160, 30);

        BtnSalvarCadEmf.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        BtnSalvarCadEmf.setText("Salvar");
        BtnSalvarCadEmf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalvarCadEmf.setEnabled(false);
        BtnSalvarCadEmf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarCadEmfActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalvarCadEmf);
        BtnSalvarCadEmf.setBounds(640, 130, 80, 30);

        CampoSenha.setEnabled(false);
        getContentPane().add(CampoSenha);
        CampoSenha.setBounds(90, 230, 160, 30);

        BTNpesquisaEnfermeiro.setText("Pesquisar");
        BTNpesquisaEnfermeiro.setEnabled(false);
        BTNpesquisaEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpesquisaEnfermeiroActionPerformed(evt);
            }
        });
        getContentPane().add(BTNpesquisaEnfermeiro);
        BTNpesquisaEnfermeiro.setBounds(300, 80, 90, 23);

        pesqEnf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pesqEnf.setText("Pesquisar Usuários");
        getContentPane().add(pesqEnf);
        pesqEnf.setBounds(46, 44, 150, 20);

        jTextFieldpesquisa.setEnabled(false);
        jTextFieldpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldpesquisa);
        jTextFieldpesquisa.setBounds(210, 40, 260, 30);

        lablCOnfSenha.setText("Confirmar Senha :");
        getContentPane().add(lablCOnfSenha);
        lablCOnfSenha.setBounds(290, 230, 110, 30);

        CampoConfSenha.setEnabled(false);
        getContentPane().add(CampoConfSenha);
        CampoConfSenha.setBounds(400, 230, 160, 30);

        BTNEcluir.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        BTNEcluir.setText("Excluir");
        BTNEcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNEcluir.setEnabled(false);
        BTNEcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BTNEcluir);
        BTNEcluir.setBounds(640, 250, 80, 30);

        BtnEditar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditar);
        BtnEditar.setBounds(640, 190, 80, 30);

        CampMatricula.setEnabled(false);
        CampMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampMatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(CampMatricula);
        CampMatricula.setBounds(70, 280, 50, 30);

        LBLCOdigo.setText("Codigo :");
        getContentPane().add(LBLCOdigo);
        LBLCOdigo.setBounds(30, 280, 50, 30);

        QuadroLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(QuadroLBL);
        QuadroLBL.setBounds(4, 34, 630, 320);

        BTNnovo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        BTNnovo.setText("Novo");
        BTNnovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNnovoActionPerformed(evt);
            }
        });
        getContentPane().add(BTNnovo);
        BTNnovo.setBounds(640, 80, 80, 30);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 310, 61, 23);

        setSize(new java.awt.Dimension(737, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarCadEmfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarCadEmfActionPerformed
       
      if(flag==1){         
           
      // seta os valores
        modenf.setNome(campoNome.getText());
        modenf.setSenha(CampoSenha.getText());
        modenf.setCargo(CampoCArgo.getText());
        control.Salvar(modenf);
        
       //// depois que salvar ele limpa os campos para cadastrar de novo////////////
         // pronto para gravar
        campoNome.setText(" ");
        CampoSenha.setText(" ");
        CampoCArgo.setText(" ");
    } else{
            modenf.setCodigouser(Integer.parseInt(CampMatricula.getText()));
            modenf.setCargo(CampoCArgo.getText());
            modenf.setSenha(CampoSenha.getText());
            modenf.setNome(campoNome.getText());
            control.Editar(modenf);       

        }
           
        
        
    }//GEN-LAST:event_BtnSalvarCadEmfActionPerformed

    private void BTNpesquisaEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpesquisaEnfermeiroActionPerformed
        
  
       modenf.setPesquisa(jTextFieldpesquisa.getText());
       ModUsuario pega = control.BuscaEnf(modenf);
        
        
        campoNome.setText(pega.getNome());
        CampoCArgo.setText(pega.getCargo()); 
        CampMatricula.setText(String.valueOf(pega.getCodigouser()));
      
        
    }//GEN-LAST:event_BTNpesquisaEnfermeiroActionPerformed

    private void jTextFieldpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpesquisaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldpesquisaActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
       
     flag = 2;
       //////////libera os botoes/////////
        
        BTNpesquisaEnfermeiro.setEnabled(true);  jTextFieldpesquisa.setEnabled(true);
        BTNEcluir.setEnabled(true);
        BtnSalvarCadEmf.setEnabled(true);
        
        //////////LIbera os campos//////////////
        campoNome.setEnabled(true);
        CampoCArgo.setEnabled(true);
        CampoSenha.setEnabled(true);
        CampoConfSenha.setEnabled(true);
        
        //////////Bloqueia os campos//////////
        BTNnovo.setEnabled(false);
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BTNEcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEcluirActionPerformed
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir ?");
        if(resposta == JOptionPane.YES_OPTION){
            modenf.setCodigouser(Integer.parseInt(CampMatricula.getText()));
            control.Excluir(modenf);
        }
        
        
        
        
    }//GEN-LAST:event_BTNEcluirActionPerformed

    private void BTNnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNnovoActionPerformed
        
        flag = 1;
        
        ///////Libera os campos////////
            campoNome.setEnabled(true);
            CampoCArgo.setEnabled(true);
            CampoSenha.setEnabled(true);
            CampoConfSenha.setEnabled(true);
            BtnSalvarCadEmf.setEnabled(true);
            
           ////////// Bloqueia campos///////
           BtnEditar.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_BTNnovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        TelaLogon recebe = new TelaLogon();
        recebe.setVisible(true);
        dispose();


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CampMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEcluir;
    private javax.swing.JButton BTNnovo;
    private javax.swing.JButton BTNpesquisaEnfermeiro;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnSalvarCadEmf;
    private javax.swing.JLabel CagoFormEmf;
    private javax.swing.JTextField CampMatricula;
    private javax.swing.JTextField CampoCArgo;
    private javax.swing.JPasswordField CampoConfSenha;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JLabel CorenFormEmf;
    private javax.swing.JLabel LBLCOdigo;
    private javax.swing.JLabel NomeFormEmf;
    private javax.swing.JLabel QuadroLBL;
    private javax.swing.JTextField campoNome;
    private javax.swing.JLabel fundCadEmf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldpesquisa;
    private javax.swing.JLabel lablCOnfSenha;
    private javax.swing.JLabel pesqEnf;
    // End of variables declaration//GEN-END:variables
}
