/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.Aluno;
import Controle.ConexaoBancoDados;
import Modelo.ModAluno;

import javax.swing.JOptionPane;

/**
 *
 * @author Hiêgo
 */
public class CadastroAlunos extends javax.swing.JFrame {
    
////// instanciando as 2 classes /////////////////    
    
    ModAluno modaluno = new ModAluno();
    Aluno controlAluno = new Aluno();
 
    
    ConexaoBancoDados conecta = new ConexaoBancoDados();
   
    int flag = 0;
    
    
    public CadastroAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rodapeTOPO = new javax.swing.JLabel();
        LablNome = new javax.swing.JLabel();
        camponome = new javax.swing.JTextField();
        LablDaTaNAS = new javax.swing.JLabel();
        campoDatNas = new javax.swing.JFormattedTextField();
        LablNomPai = new javax.swing.JLabel();
        campoNomPai = new javax.swing.JTextField();
        LablNomMae = new javax.swing.JLabel();
        campoNomMae = new javax.swing.JTextField();
        LablEnde = new javax.swing.JLabel();
        campEnde = new javax.swing.JTextField();
        LabSexo = new javax.swing.JLabel();
        campoSexo = new javax.swing.JTextField();
        BtnNovo = new javax.swing.JButton();
        BtnSalvar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pesquisar = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BTNPesquisar = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        jLabelNomeEscola = new javax.swing.JLabel();
        CampoCurso = new javax.swing.JTextField();
        jLabelNomeCurso = new javax.swing.JLabel();
        campopesquisar = new javax.swing.JTextField();
        CampoNomeEscola = new javax.swing.JTextField();
        cadastpascientes = new javax.swing.JLabel();
        BTNvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        rodapeTOPO.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rodapeTOPO.setText("Cadastro de Alunos");
        rodapeTOPO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(rodapeTOPO);
        rodapeTOPO.setBounds(320, 0, 400, 30);

        LablNome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LablNome.setText("Nome :");
        getContentPane().add(LablNome);
        LablNome.setBounds(40, 140, 60, 20);

        camponome.setEnabled(false);
        getContentPane().add(camponome);
        camponome.setBounds(100, 130, 360, 30);

        LablDaTaNAS.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LablDaTaNAS.setText("Data Nascimento :");
        getContentPane().add(LablDaTaNAS);
        LablDaTaNAS.setBounds(40, 180, 130, 30);

        try {
            campoDatNas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDatNas.setEnabled(false);
        campoDatNas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDatNasActionPerformed(evt);
            }
        });
        getContentPane().add(campoDatNas);
        campoDatNas.setBounds(170, 180, 110, 30);

        LablNomPai.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LablNomPai.setText("Nome do Pai :");
        getContentPane().add(LablNomPai);
        LablNomPai.setBounds(360, 180, 100, 30);

        campoNomPai.setEnabled(false);
        campoNomPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomPaiActionPerformed(evt);
            }
        });
        getContentPane().add(campoNomPai);
        campoNomPai.setBounds(460, 180, 290, 30);

        LablNomMae.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LablNomMae.setText("Nome da Mãe :");
        getContentPane().add(LablNomMae);
        LablNomMae.setBounds(40, 230, 100, 30);

        campoNomMae.setEnabled(false);
        campoNomMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomMaeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNomMae);
        campoNomMae.setBounds(140, 230, 290, 30);

        LablEnde.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LablEnde.setText("Endereço :");
        getContentPane().add(LablEnde);
        LablEnde.setBounds(480, 230, 90, 30);

        campEnde.setEnabled(false);
        campEnde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campEndeActionPerformed(evt);
            }
        });
        getContentPane().add(campEnde);
        campEnde.setBounds(560, 230, 140, 30);

        LabSexo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        LabSexo.setText("Sexo :");
        getContentPane().add(LabSexo);
        LabSexo.setBounds(510, 130, 50, 30);

        campoSexo.setEnabled(false);
        campoSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSexoActionPerformed(evt);
            }
        });
        getContentPane().add(campoSexo);
        campoSexo.setBounds(560, 130, 140, 30);

        BtnNovo.setText("Novo");
        BtnNovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNovo);
        BtnNovo.setBounds(40, 410, 70, 30);

        BtnSalvar1.setText("Salvar");
        BtnSalvar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnSalvar1.setEnabled(false);
        BtnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvar1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalvar1);
        BtnSalvar1.setBounds(430, 410, 70, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 390, 760, 60);

        pesquisar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pesquisar.setText("Pesquisar Alunos :");
        getContentPane().add(pesquisar);
        pesquisar.setBounds(110, 30, 260, 30);

        BtnEditar.setText("Editar");
        BtnEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEditar.setEnabled(false);
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditar);
        BtnEditar.setBounds(230, 410, 70, 30);

        BtnExcluir.setText("Excluir");
        BtnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnExcluir.setEnabled(false);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExcluir);
        BtnExcluir.setBounds(670, 410, 70, 30);

        BTNPesquisar.setText("Pesquisar");
        BTNPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNPesquisar);
        BTNPesquisar.setBounds(410, 70, 90, 30);

        jLabelID.setText("ID :");
        jLabelID.setEnabled(false);
        getContentPane().add(jLabelID);
        jLabelID.setBounds(40, 94, 18, 30);

        campoID.setEnabled(false);
        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });
        getContentPane().add(campoID);
        campoID.setBounds(60, 95, 55, 30);

        jLabelNomeEscola.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNomeEscola.setText("Nome da Escola :");
        getContentPane().add(jLabelNomeEscola);
        jLabelNomeEscola.setBounds(40, 310, 160, 30);
        getContentPane().add(CampoCurso);
        CampoCurso.setBounds(170, 350, 340, 30);

        jLabelNomeCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNomeCurso.setText("Nome do Curso :");
        getContentPane().add(jLabelNomeCurso);
        jLabelNomeCurso.setBounds(40, 350, 110, 30);

        campopesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campopesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(campopesquisar);
        campopesquisar.setBounds(340, 30, 240, 30);

        CampoNomeEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeEscolaActionPerformed(evt);
            }
        });
        getContentPane().add(CampoNomeEscola);
        CampoNomeEscola.setBounds(170, 310, 340, 30);

        cadastpascientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastpascientes.setEnabled(false);
        getContentPane().add(cadastpascientes);
        cadastpascientes.setBounds(20, 20, 760, 430);

        BTNvoltar.setText("Voltar");
        BTNvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNvoltar);
        BTNvoltar.setBounds(360, 460, 60, 23);

        setSize(new java.awt.Dimension(819, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDatNasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDatNasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDatNasActionPerformed

    private void campoSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSexoActionPerformed

    private void BtnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvar1ActionPerformed

        if(flag==1){ // SE A FLAG É "1", ESTA É UM NOVO PACIENTE
            
    // AO CLICAR EM SALVAR O BOTAO E A BARRA DE PESQUISA E LIBERADA
        campopesquisar.setEnabled(true);
        BTNPesquisar.setEnabled(true);
        BtnNovo.setEnabled(true);
        BtnEditar.setEnabled(false);
        
    //////////////////////////////////////////////////////////////        
    ///   Aluno  PEGA OS DADOS DIGITADOS PARA SALVA            ///
    //////////////////////////////////////////////////////////////
       modaluno.setNome(camponome.getText());
       modaluno.setNomepai(campoNomPai.getText());
       modaluno.setNomemae(campoNomMae.getText());
       modaluno.setSexo(campoSexo.getText());
       modaluno.setEndereco(campEnde.getText());
       modaluno.setNascimento(campoDatNas.getText());
       modaluno.setEscola(CampoNomeEscola.getText());
       modaluno.setCurso(CampoCurso.getText());
       controlAluno.Salvar(modaluno);
       
    // APÓS SALVAR A TELA
    // LIMPA E TRAVA OS CAMPOS DE INSERIR DADOS
        camponome.setText(null);          camponome.setEnabled(false);
        campoNomPai.setText(null);        campoNomPai.setEnabled(false);
        campoNomMae.setText(null);        campoNomMae.setEnabled(false);
        campoSexo.setText(null);          campoSexo.setEnabled(false);
        campEnde.setText(null);           campEnde.setEnabled(false);
        campoDatNas.setText(null);        campoDatNas.setEnabled(false);
       CampoNomeEscola.setText(null);    CampoNomeEscola.setEnabled(false);
       CampoCurso.setText(null);         CampoCurso.setEnabled(false);


    //////////////////////////////////////////////////////////////////////   
        
        
      } else { // SE NÃO É UMA NOVA ADIÇÃO, É UMA EDIÇÃO, LOGO PEGA OS NOVOS DADOS:
          
    /////////////////////////////////////////////////////////////////////        
    // aluno  PEGA OS DADOS DO BANCO PARA EDITAR CONFORME PESQUISADO //// 
    ///////////////////////////////////////////////////////////////////
    
        modaluno.setCodigo(Integer.parseInt(campoID.getText()));
      // modaluno.setCodigo(Integer.parseInt(campoID.getText()));
       modaluno.setNome(camponome.getText());
       modaluno.setNomepai(campoNomPai.getText());
       modaluno.setNomemae(campoNomMae.getText());
       modaluno.setSexo(campoSexo.getText());
       modaluno.setEndereco(campEnde.getText());
       modaluno.setNascimento(campoDatNas.getText());
       modaluno.setEscola(CampoNomeEscola.getText());
       modaluno.setCurso(CampoCurso.getText());
       controlAluno.Editar(modaluno); // envia pro banco os elementos editados
     
    
       
       // LIMPA E TRAVA OS CAMPOS DE INSERIR DADOS
        BtnSalvar1.setEnabled(false);
        campoID.setText(null);        campoID.setEnabled(false);
        camponome.setText(null);      camponome.setEnabled(false);
        jLabelID.setText(null);       jLabelID.setEnabled(false);
        campoSexo.setText(null);      campoSexo.setEnabled(false);
        campoDatNas.setText(null);    campoDatNas.setEnabled(false);
        campoNomPai.setText(null);    campoNomPai.setEnabled(false);
        campoNomMae.setText(null);    campoNomMae.setEnabled(false);
        campEnde.setText(null);       campEnde.setEnabled(false);
        CampoNomeEscola.setText(null);                CampoNomeEscola.setEnabled(false);
       
       // LIBERA NOVAMENTE A PESQUISA
        BTNPesquisar.setEnabled(true);
        BtnNovo.setEnabled(true);
        campopesquisar.setEnabled(true);
        BTNPesquisar.setEnabled(true);
       
      }
  
    }//GEN-LAST:event_BtnSalvar1ActionPerformed

    private void campoNomPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomPaiActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir ?");
        if(resposta == JOptionPane.YES_OPTION){
            modaluno.setCodigo(Integer.parseInt(campoID.getText()));
            controlAluno.Excluir(modaluno);
        }
                    
        
        
        
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void campopesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campopesquisarActionPerformed
            
    }//GEN-LAST:event_campopesquisarActionPerformed

    private void BTNPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPesquisarActionPerformed
     ////LIBERA BOTOES////////////////////  
       BtnEditar.setEnabled(true);
       BtnExcluir.setEnabled(true);
    ////////////////////////////////////////    
      modaluno.setPesquisa(campopesquisar.getText());
      ModAluno modell = controlAluno.BuscaAluno(modaluno);
       
       
        campoID.setText(String.valueOf(modell.getCodigo()));
        camponome.setText(modell.getNome());
        campoNomPai.setText(modell.getNomepai());
        campoNomMae.setText(modell.getNomemae());
        campoSexo.setText(modell.getSexo());
        campoDatNas.setText(modell.getNascimento());
        campEnde.setText(modell.getEndereco());
        CampoNomeEscola.setText(modell.getEscola());
        CampoCurso.setText(modell.getCurso());
   
        
    
        
    }//GEN-LAST:event_BTNPesquisarActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        flag = 1;
        
// Limpa todos os dados da tela (Caso o "NOVO" seja clicado após a pesquisa que
// retornou dados e preencheu os campos.

        campoID.setText(null);
        camponome.setText(null);
        campoSexo.setText(null);
        campoDatNas.setText(null);
        campoNomPai.setText(null);
        campoNomMae.setText(null); 
        campEnde.setText(null);
        CampoNomeEscola.setText(null);


        
// ao clicar no botao novo ele LIBERA o botao salvar
        BtnSalvar1.setEnabled(true);
        campoID.setEnabled(false);
        campopesquisar.setEnabled(false);
        BTNPesquisar.setEnabled(false);
        BtnEditar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        camponome.setEnabled(true);
        campoSexo.setEnabled(true);
        campoDatNas.setEnabled(true);
        campoNomPai.setEnabled(true);
        campoNomMae.setEnabled(true);
        campEnde.setEnabled(true);
        CampoNomeEscola.setEnabled(true);

    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
      
        flag=2 ;
//////////bloqueia os campos/////////
        BTNPesquisar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        BtnNovo.setEnabled(false);
        campopesquisar.setEnabled(false);
        BTNPesquisar.setEnabled(false);
        
        
        ///////libera os campos///////////
        BtnSalvar1.setEnabled(true);
        camponome.setEnabled(true);
        campoSexo.setEnabled(true);
        campoDatNas.setEnabled(true);
        campoNomPai.setEnabled(true);
        campoNomMae.setEnabled(true);
        campEnde.setEnabled(true);
        CampoNomeEscola.setEnabled(true);
        CampoCurso.setEnabled(true);


           
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void BTNvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNvoltarActionPerformed
        SegundoPlano recebe = new SegundoPlano();
        recebe.setVisible(true);
        dispose();

    }//GEN-LAST:event_BTNvoltarActionPerformed

    private void CampoNomeEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeEscolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeEscolaActionPerformed

    private void campEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campEndeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campEndeActionPerformed

    private void campoNomMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomMaeActionPerformed
        // TODO add your handling code here:

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNPesquisar;
    private javax.swing.JButton BTNvoltar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnSalvar1;
    private javax.swing.JTextField CampoCurso;
    private javax.swing.JTextField CampoNomeEscola;
    private javax.swing.JLabel LabSexo;
    private javax.swing.JLabel LablDaTaNAS;
    private javax.swing.JLabel LablEnde;
    private javax.swing.JLabel LablNomMae;
    private javax.swing.JLabel LablNomPai;
    private javax.swing.JLabel LablNome;
    private javax.swing.JLabel cadastpascientes;
    private javax.swing.JTextField campEnde;
    private javax.swing.JFormattedTextField campoDatNas;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNomMae;
    private javax.swing.JTextField campoNomPai;
    private javax.swing.JTextField campoSexo;
    private javax.swing.JTextField camponome;
    private javax.swing.JTextField campopesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNomeCurso;
    private javax.swing.JLabel jLabelNomeEscola;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JLabel rodapeTOPO;
    // End of variables declaration//GEN-END:variables
}
