/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConexaoBancoDados;
import Modelo.ModTable;
import java.awt.List;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Hiego
 */
public class Relatorio extends javax.swing.JFrame {

    ConexaoBancoDados conecta = new ConexaoBancoDados();
    
    
    
    public Relatorio() {
        initComponents();
        conecta.Conexao();
        preencherTabela("select nome,nomeesc,cursounv,nomeunv,cnpjunv from aluno A,escolas B,universidades C  where A.codigo = B.codigoesc and B.codigoesc = C.codigounv");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoBuscarAlunos = new javax.swing.JTextField();
        jButtonBuscarAlunos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        BtnVoltar_verificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pesquisar Alunos :");

        CampoBuscarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscarAlunosActionPerformed(evt);
            }
        });

        jButtonBuscarAlunos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscarAlunos.setText("Buscar");

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableAlunos);

        BtnVoltar_verificar.setText("Voltar");
        BtnVoltar_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltar_verificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(CampoBuscarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBuscarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnVoltar_verificar)
                        .addGap(350, 350, 350))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoBuscarAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnVoltar_verificar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoBuscarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscarAlunosActionPerformed
        
        preencherTabela("select nome,nomeesc,cursounv,nomeunv,cnpjunv from aluno A,escolas B,universidades C  where A.codigo = B.codigoesc and B.codigoesc = C.codigounv and nome ilike '%"+CampoBuscarAlunos.getText()+"%'");

    }//GEN-LAST:event_CampoBuscarAlunosActionPerformed

    private void BtnVoltar_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltar_verificarActionPerformed
        SegundoPlano recebe = new SegundoPlano();
        recebe.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BtnVoltar_verificarActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
      //  List<Object> lista = new ArrayList<Object>
        String [] colunas = new String[]{"Nome","Escola","Curso","Universidade","CNPJ Universidade"};
        
        conecta.executaSQL(Sql);
        
        try {
            conecta.rs.first();

            do{
             //while(conecta.rs.next()){
                 dados.add(new Object[]{conecta.rs.getString("nome"),conecta.rs.getString("nomeesc"),
                     conecta.rs.getString("cursounv"),conecta.rs.getString("nomeunv"),
                     conecta.rs.getString("cnpjunv")   });
                 
                
            }while(conecta.rs.next()); 
           
            
            
        } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "ERRO AO PREENCHER A VETOR!!  \n " + ex.getMessage());

        }
        
        ModTable modelo = new ModTable(dados, colunas);
        
        jTableAlunos.setModel(modelo);
        
        jTableAlunos.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableAlunos.getColumnModel().getColumn(0).setResizable(false);
        
        jTableAlunos.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableAlunos.getColumnModel().getColumn(1).setResizable(false);
        
        jTableAlunos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableAlunos.getColumnModel().getColumn(2).setResizable(false);
        
        jTableAlunos.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableAlunos.getColumnModel().getColumn(3).setResizable(false);
        
        jTableAlunos.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableAlunos.getColumnModel().getColumn(4).setResizable(false);
        
        jTableAlunos.getTableHeader().setReorderingAllowed(false);
        jTableAlunos.setAutoResizeMode(jTableAlunos.AUTO_RESIZE_OFF);
        jTableAlunos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        
       conecta.Desconecta();
      
    }
    
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVoltar_verificar;
    private javax.swing.JTextField CampoBuscarAlunos;
    private javax.swing.JButton jButtonBuscarAlunos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlunos;
    // End of variables declaration//GEN-END:variables
}
