/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConexaoBancoDados;
import Controle.Aluno;
import Controle.Usuario;
import java.awt.Toolkit;
import javax.swing.JFrame;

import javax.swing.JOptionPane;


/**
 *
 * @author Hiêgo
 */
public class TelaLogon extends javax.swing.JFrame {

   
    ConexaoBancoDados conecta = new ConexaoBancoDados();
    
    public TelaLogon() {
        initComponents();
        conecta.Conexao();//instanciando o obejto conecta e chamando o metodo de conexao
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        camponome = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        camposenha = new javax.swing.JPasswordField();
        Acessar = new javax.swing.JButton();
        BtnCadastrarU = new javax.swing.JButton();
        FundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso CyberSchool");
        getContentPane().setLayout(null);

        login.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        login.setText("Login :");
        getContentPane().add(login);
        login.setBounds(290, 150, 50, 30);

        camponome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomeActionPerformed(evt);
            }
        });
        getContentPane().add(camponome);
        camponome.setBounds(360, 150, 220, 30);

        senha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        senha.setText("Senha :");
        getContentPane().add(senha);
        senha.setBounds(290, 220, 60, 30);
        getContentPane().add(camposenha);
        camposenha.setBounds(360, 220, 220, 30);

        Acessar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        Acessar.setText("Acessar");
        Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessarActionPerformed(evt);
            }
        });
        getContentPane().add(Acessar);
        Acessar.setBounds(430, 280, 90, 40);

        BtnCadastrarU.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        BtnCadastrarU.setText("Cadastro para fazer login");
        BtnCadastrarU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCadastrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarUActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadastrarU);
        BtnCadastrarU.setBounds(380, 360, 190, 30);

        FundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotela.jpeg"))); // NOI18N
        getContentPane().add(FundoTela);
        FundoTela.setBounds(0, 0, 660, 450);

        setSize(new java.awt.Dimension(671, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// ao clicar em acessar chamara a proxima tela
    private void AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessarActionPerformed
       
        Usuario ctrl = new Usuario(); 
       if(ctrl.CheckLogin(camponome.getText(), camposenha.getText())){
           
       new SegundoPlano().setVisible(true);
       dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Usuário ou senha Inconrreto");
       }
        
        /*CadastroPacientes recebe = new CadastroPacientes();
        recebe.setVisible(true);
        dispose();// quando chamar a proxima tela anterior fechara
        
        */
      
    }//GEN-LAST:event_AcessarActionPerformed

    private void camponomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camponomeActionPerformed

    private void BtnCadastrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarUActionPerformed
     
 
      CadastroUsuario form = new CadastroUsuario();
      form.setVisible(true);
      dispose();
           
        
      
        
    }//GEN-LAST:event_BtnCadastrarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new TelaLogon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acessar;
    private javax.swing.JButton BtnCadastrarU;
    private javax.swing.JLabel FundoTela;
    private javax.swing.JTextField camponome;
    private javax.swing.JPasswordField camposenha;
    private javax.swing.JLabel login;
    private javax.swing.JLabel senha;
    // End of variables declaration//GEN-END:variables


}
